using Microsoft.VisualStudio.TestTools.UnitTesting;
using FFireManage.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FFireManage.Service.Tests
{
    [TestClass()]
    public class FireDocumentControllerTests
    {
        [TestMethod()]
        public void GetTest()
        {
            FireDocumentController fireDocumentController;
            Dictionary<string, object> dictionary;
            // 测试用例1
            fireDocumentController = new FireDocumentController();
            fireDocumentController.Get((Dictionary<string, object>)null);
            Assert.IsNotNull((object)fireDocumentController);
            Assert.AreEqual<string>
                ("127.0.0.1", ((BaseService)fireDocumentController).Server);
            Assert.AreEqual<int>(8080, ((BaseService)fireDocumentController).Port);
            //测试用例2
            fireDocumentController = new FireDocumentController();
            dictionary = new Dictionary<string, object>(0);
            dictionary[""] = (object)null;
            fireDocumentController.Get(dictionary);
            Assert.IsNotNull((object)fireDocumentController);
            Assert.AreEqual<string>
                ("127.0.0.1", ((BaseService)fireDocumentController).Server);
            Assert.AreEqual<int>(8080, ((BaseService)fireDocumentController).Port);
        }

        [TestMethod()]
        public void AddTest()
        {
            FireDocumentController fireDocumentController;
            // 测试用例1
            fireDocumentController = new FireDocumentController();
            fireDocumentController.Add((Fire_Document)null);
            Assert.IsNotNull((object)fireDocumentController);
            Assert.AreEqual<string>
                ("127.0.0.1", ((BaseService)fireDocumentController).Server);
            Assert.AreEqual<int>(8080, ((BaseService)fireDocumentController).Port);
            // 测试用例2
            fireDocumentController = new FireDocumentController();
            Fire_Document s0 = new Fire_Document();
            s0.OBJECTID = 0;
            s0.shape = (string)null;
            s0.city = (string)null;
            s0.county = (string)null;
            s0.no = (string)null;
            s0.hotid = (string)null;
            s0.name = (string)null;
            s0.address = (string)null;
            s0.longitude = default(double?);
            s0.latitude = default(double?);
            s0.s_time = (string)null;
            s0.f_time = (string)null;
            s0.e_time = (string)null;
            s0.duration = default(double?);
            s0.firetype = (string)null;
            s0.cause = (string)null;
            s0.firearea = default(double?);
            s0.nf_area = default(double?);
            s0.af_proport = default(double?);
            s0.t_categ = (string)null;
            s0.ta_categ = (string)null;
            s0.d_categ = (string)null;
            s0.treeform = (string)null;
            s0.woodloss = default(double?);
            s0.iwoodloss = default(double?);
            s0.saplloss = default(double?);
            s0.inj_minor = default(int?);
            s0.inj_severe = default(int?);
            s0.inj_death = default(int?);
            s0.conductor = (string)null;
            s0.con_post = (string)null;
            s0.brigade = default(int?);
            s0.for_police = default(int?);
            s0.army = default(int?);
            s0.arm_police = default(int?);
            s0.masses = default(int?);
            s0.plane = default(int?);
            s0.planetype = (string)null;
            s0.flighttime = default(double?);
            s0.flightcost = default(double?);
            s0.planefall = default(int?);
            s0.fallpeople = default(int?);
            s0.p_chemical = default(int?);
            s0.p_bucket = default(int?);
            s0.commandcar = default(int?);
            s0.trans_car = default(int?);
            s0.armoredcar = default(int?);
            s0.othercar = default(int?);
            s0.shortwave = default(int?);
            s0.uswave = default(int?);
            s0.windequip = default(int?);
            s0.watergun = default(int?);
            s0.n2n3tool = default(int?);
            s0.otherequip = default(int?);
            s0.fightcost = default(double?);
            s0.otherloss = default(double?);
            s0.wrecker = (string)null;
            s0.wreckerage = 0;
            s0.wreckerpro = (string)null;
            s0.wreckerunit = (string)null;
            s0.wapunish = (string)null;
            s0.wcpunish = (string)null;
            s0.hapunish = (string)null;
            s0.hcpunish = (string)null;
            s0.tempera = default(double?);
            s0.humidity = default(double?);
            s0.winddir = (string)null;
            s0.windpower = (string)null;
            s0.windspeed = default(double?);
            s0.rainfall = default(double?);
            s0.description = (string)null;
            s0.cre_time = (string)null;
            s0.cre_pers = (string)null;
            s0.mod_time = (string)null;
            s0.mod_pers = (string)null;
            s0.picture1 = (string)null;
            s0.picture2 = (string)null;
            s0.video = (string)null;
            s0.id = (string)null;
            s0.province = (string)null;
            s0.town_name = (string)null;
            s0.village_name = (string)null;
            s0.elevation = default(double?);
            s0.aspect = (string)null;
            s0.slope_position = (string)null;
            s0.slope = default(double?);
            s0.land_type = (string)null;
            s0.front_command_name = (string)null;
            s0.front_command_post = (string)null;
            s0.rear_command_name = (string)null;
            s0.rear_command_post = (string)null;
            s0.cadre = default(int?);
            s0.for_cop = default(int?);
            s0.brigade_people = default(int?);
            s0.hbrigade_people = default(int?);
            s0.hbrigade = default(int?);
            s0.communication_car = default(int?);
            s0.support_car = default(int?);
            s0.hpw_tanker = default(int?);
            s0.bulldozer = default(int?);
            s0.interphone = default(int?);
            s0.satellitephone = default(int?);
            s0.other_communication = default(int?);
            s0.nav_handheld = default(int?);
            s0.nav_vehicle = default(int?);
            s0.high_pressure_fex = default(int?);
            s0.pump = default(int?);
            s0.artificial_rain = default(double?);
            s0.fire_bombs = default(int?);
            s0.b_cutter = default(int?);
            s0.chainsaw = default(int?);
            s0.camera1 = default(int?);
            s0.camera2 = default(int?);
            s0.caseInfo = (string)null;
            s0.wayofaccident = (string)null;
            s0.weather = (string)null;
            s0.high_tempera = default(double?);
            s0.low_tempera = default(double?);
            s0.low_humidity = default(double?);
            s0.code = (string)null;
            s0.forestarea = default(double?);
            s0.newforestarea = default(double?);
            s0.artificialfireout = default(int?);
            s0.totavehiclenumber = default(int?);
            s0.carnumber = default(int?);
            s0.planeoutnumber = default(int?);
            s0.WingAirPlaneNumber = default(int?);
            s0.WingAirPlaneTime = default(int?);
            s0.HelicopterNumber = default(int?);
            s0.HelicopterTime = default(int?);
            s0.WuRenJiNumber = default(int?);
            s0.WuRenjiTime = default(int?);
            s0.IsDealWith = default(int?);
            s0.ProcessedNumber = default(int?);
            s0.CriminalNumber = default(int?);
            s0.APenaltyNumber = default(int?);
            s0.ASanctionNumber = default(int?);
            s0.RecordDispositionNumber = default(int?);
            s0.Reporter = (string)null;
            s0.ReportTime = (string)null;
            s0.pac = (string)null;
            s0.mediaByteDict = (Dictionary<string, object>)null;
            s0.mediaFiles = (List<MediaFile>)null;
            fireDocumentController.Add(s0);
            Assert.IsNotNull((object)fireDocumentController);
            Assert.AreEqual<string>
                ("127.0.0.1", ((BaseService)fireDocumentController).Server);
            Assert.AreEqual<int>(8080, ((BaseService)fireDocumentController).Port);
            // 测试用例3
            fireDocumentController = new FireDocumentController();
            s0 = new Fire_Document();
            s0.OBJECTID = 0;
            s0.shape = "";
            s0.city = (string)null;
            s0.county = (string)null;
            s0.no = (string)null;
            s0.hotid = (string)null;
            s0.name = (string)null;
            s0.address = (string)null;
            s0.longitude = default(double?);
            s0.latitude = default(double?);
            s0.s_time = (string)null;
            s0.f_time = (string)null;
            s0.e_time = (string)null;
            s0.duration = default(double?);
            s0.firetype = (string)null;
            s0.cause = (string)null;
            s0.firearea = default(double?);
            s0.nf_area = default(double?);
            s0.af_proport = default(double?);
            s0.t_categ = (string)null;
            s0.ta_categ = (string)null;
            s0.d_categ = (string)null;
            s0.treeform = (string)null;
            s0.woodloss = default(double?);
            s0.iwoodloss = default(double?);
            s0.saplloss = default(double?);
            s0.inj_minor = default(int?);
            s0.inj_severe = default(int?);
            s0.inj_death = default(int?);
            s0.conductor = (string)null;
            s0.con_post = (string)null;
            s0.brigade = default(int?);
            s0.for_police = default(int?);
            s0.army = default(int?);
            s0.arm_police = default(int?);
            s0.masses = default(int?);
            s0.plane = default(int?);
            s0.planetype = (string)null;
            s0.flighttime = default(double?);
            s0.flightcost = default(double?);
            s0.planefall = default(int?);
            s0.fallpeople = default(int?);
            s0.p_chemical = default(int?);
            s0.p_bucket = default(int?);
            s0.commandcar = default(int?);
            s0.trans_car = default(int?);
            s0.armoredcar = default(int?);
            s0.othercar = default(int?);
            s0.shortwave = default(int?);
            s0.uswave = default(int?);
            s0.windequip = default(int?);
            s0.watergun = default(int?);
            s0.n2n3tool = default(int?);
            s0.otherequip = default(int?);
            s0.fightcost = default(double?);
            s0.otherloss = default(double?);
            s0.wrecker = (string)null;
            s0.wreckerage = 0;
            s0.wreckerpro = (string)null;
            s0.wreckerunit = (string)null;
            s0.wapunish = (string)null;
            s0.wcpunish = (string)null;
            s0.hapunish = (string)null;
            s0.hcpunish = (string)null;
            s0.tempera = default(double?);
            s0.humidity = default(double?);
            s0.winddir = (string)null;
            s0.windpower = (string)null;
            s0.windspeed = default(double?);
            s0.rainfall = default(double?);
            s0.description = (string)null;
            s0.cre_time = (string)null;
            s0.cre_pers = (string)null;
            s0.mod_time = (string)null;
            s0.mod_pers = (string)null;
            s0.picture1 = (string)null;
            s0.picture2 = (string)null;
            s0.video = (string)null;
            s0.id = (string)null;
            s0.province = (string)null;
            s0.town_name = (string)null;
            s0.village_name = (string)null;
            s0.elevation = default(double?);
            s0.aspect = (string)null;
            s0.slope_position = (string)null;
            s0.slope = default(double?);
            s0.land_type = (string)null;
            s0.front_command_name = (string)null;
            s0.front_command_post = (string)null;
            s0.rear_command_name = (string)null;
            s0.rear_command_post = (string)null;
            s0.cadre = default(int?);
            s0.for_cop = default(int?);
            s0.brigade_people = default(int?);
            s0.hbrigade_people = default(int?);
            s0.hbrigade = default(int?);
            s0.communication_car = default(int?);
            s0.support_car = default(int?);
            s0.hpw_tanker = default(int?);
            s0.bulldozer = default(int?);
            s0.interphone = default(int?);
            s0.satellitephone = default(int?);
            s0.other_communication = default(int?);
            s0.nav_handheld = default(int?);
            s0.nav_vehicle = default(int?);
            s0.high_pressure_fex = default(int?);
            s0.pump = default(int?);
            s0.artificial_rain = default(double?);
            s0.fire_bombs = default(int?);
            s0.b_cutter = default(int?);
            s0.chainsaw = default(int?);
            s0.camera1 = default(int?);
            s0.camera2 = default(int?);
            s0.caseInfo = (string)null;
            s0.wayofaccident = (string)null;
            s0.weather = (string)null;
            s0.high_tempera = default(double?);
            s0.low_tempera = default(double?);
            s0.low_humidity = default(double?);
            s0.code = (string)null;
            s0.forestarea = default(double?);
            s0.newforestarea = default(double?);
            s0.artificialfireout = default(int?);
            s0.totavehiclenumber = default(int?);
            s0.carnumber = default(int?);
            s0.planeoutnumber = default(int?);
            s0.WingAirPlaneNumber = default(int?);
            s0.WingAirPlaneTime = default(int?);
            s0.HelicopterNumber = default(int?);
            s0.HelicopterTime = default(int?);
            s0.WuRenJiNumber = default(int?);
            s0.WuRenjiTime = default(int?);
            s0.IsDealWith = default(int?);
            s0.ProcessedNumber = default(int?);
            s0.CriminalNumber = default(int?);
            s0.APenaltyNumber = default(int?);
            s0.ASanctionNumber = default(int?);
            s0.RecordDispositionNumber = default(int?);
            s0.Reporter = (string)null;
            s0.ReportTime = (string)null;
            s0.pac = (string)null;
            s0.mediaByteDict = (Dictionary<string, object>)null;
            s0.mediaFiles = (List<MediaFile>)null;
            fireDocumentController.Add(s0);
            Assert.IsNotNull((object)fireDocumentController);
            Assert.AreEqual<string>
                ("127.0.0.1", ((BaseService)fireDocumentController).Server);
            Assert.AreEqual<int>(8080, ((BaseService)fireDocumentController).Port);
            // 测试用例4
            Dictionary<string, object> dictionary;
            fireDocumentController = new FireDocumentController();
            dictionary = new Dictionary<string, object>();
            dictionary[""] = (object)null;
            s0 = new Fire_Document();
            s0.OBJECTID = 0;
            s0.shape = (string)null;
            s0.city = (string)null;
            s0.county = (string)null;
            s0.no = (string)null;
            s0.hotid = (string)null;
            s0.name = (string)null;
            s0.address = (string)null;
            s0.longitude = default(double?);
            s0.latitude = default(double?);
            s0.s_time = (string)null;
            s0.f_time = (string)null;
            s0.e_time = (string)null;
            s0.duration = default(double?);
            s0.firetype = (string)null;
            s0.cause = (string)null;
            s0.firearea = default(double?);
            s0.nf_area = default(double?);
            s0.af_proport = default(double?);
            s0.t_categ = (string)null;
            s0.ta_categ = (string)null;
            s0.d_categ = (string)null;
            s0.treeform = (string)null;
            s0.woodloss = default(double?);
            s0.iwoodloss = default(double?);
            s0.saplloss = default(double?);
            s0.inj_minor = default(int?);
            s0.inj_severe = default(int?);
            s0.inj_death = default(int?);
            s0.conductor = (string)null;
            s0.con_post = (string)null;
            s0.brigade = default(int?);
            s0.for_police = default(int?);
            s0.army = default(int?);
            s0.arm_police = default(int?);
            s0.masses = default(int?);
            s0.plane = default(int?);
            s0.planetype = (string)null;
            s0.flighttime = default(double?);
            s0.flightcost = default(double?);
            s0.planefall = default(int?);
            s0.fallpeople = default(int?);
            s0.p_chemical = default(int?);
            s0.p_bucket = default(int?);
            s0.commandcar = default(int?);
            s0.trans_car = default(int?);
            s0.armoredcar = default(int?);
            s0.othercar = default(int?);
            s0.shortwave = default(int?);
            s0.uswave = default(int?);
            s0.windequip = default(int?);
            s0.watergun = default(int?);
            s0.n2n3tool = default(int?);
            s0.otherequip = default(int?);
            s0.fightcost = default(double?);
            s0.otherloss = default(double?);
            s0.wrecker = (string)null;
            s0.wreckerage = 0;
            s0.wreckerpro = (string)null;
            s0.wreckerunit = (string)null;
            s0.wapunish = (string)null;
            s0.wcpunish = (string)null;
            s0.hapunish = (string)null;
            s0.hcpunish = (string)null;
            s0.tempera = default(double?);
            s0.humidity = default(double?);
            s0.winddir = (string)null;
            s0.windpower = (string)null;
            s0.windspeed = default(double?);
            s0.rainfall = default(double?);
            s0.description = (string)null;
            s0.cre_time = (string)null;
            s0.cre_pers = (string)null;
            s0.mod_time = (string)null;
            s0.mod_pers = (string)null;
            s0.picture1 = (string)null;
            s0.picture2 = (string)null;
            s0.video = (string)null;
            s0.id = (string)null;
            s0.province = (string)null;
            s0.town_name = (string)null;
            s0.village_name = (string)null;
            s0.elevation = default(double?);
            s0.aspect = (string)null;
            s0.slope_position = (string)null;
            s0.slope = default(double?);
            s0.land_type = (string)null;
            s0.front_command_name = (string)null;
            s0.front_command_post = (string)null;
            s0.rear_command_name = (string)null;
            s0.rear_command_post = (string)null;
            s0.cadre = default(int?);
            s0.for_cop = default(int?);
            s0.brigade_people = default(int?);
            s0.hbrigade_people = default(int?);
            s0.hbrigade = default(int?);
            s0.communication_car = default(int?);
            s0.support_car = default(int?);
            s0.hpw_tanker = default(int?);
            s0.bulldozer = default(int?);
            s0.interphone = default(int?);
            s0.satellitephone = default(int?);
            s0.other_communication = default(int?);
            s0.nav_handheld = default(int?);
            s0.nav_vehicle = default(int?);
            s0.high_pressure_fex = default(int?);
            s0.pump = default(int?);
            s0.artificial_rain = default(double?);
            s0.fire_bombs = default(int?);
            s0.b_cutter = default(int?);
            s0.chainsaw = default(int?);
            s0.camera1 = default(int?);
            s0.camera2 = default(int?);
            s0.caseInfo = (string)null;
            s0.wayofaccident = (string)null;
            s0.weather = (string)null;
            s0.high_tempera = default(double?);
            s0.low_tempera = default(double?);
            s0.low_humidity = default(double?);
            s0.code = (string)null;
            s0.forestarea = default(double?);
            s0.newforestarea = default(double?);
            s0.artificialfireout = default(int?);
            s0.totavehiclenumber = default(int?);
            s0.carnumber = default(int?);
            s0.planeoutnumber = default(int?);
            s0.WingAirPlaneNumber = default(int?);
            s0.WingAirPlaneTime = default(int?);
            s0.HelicopterNumber = default(int?);
            s0.HelicopterTime = default(int?);
            s0.WuRenJiNumber = default(int?);
            s0.WuRenjiTime = default(int?);
            s0.IsDealWith = default(int?);
            s0.ProcessedNumber = default(int?);
            s0.CriminalNumber = default(int?);
            s0.APenaltyNumber = default(int?);
            s0.ASanctionNumber = default(int?);
            s0.RecordDispositionNumber = default(int?);
            s0.Reporter = (string)null;
            s0.ReportTime = (string)null;
            s0.pac = (string)null;
            s0.mediaByteDict = dictionary;
            s0.mediaFiles = (List<MediaFile>)null;
            fireDocumentController.Add(s0);
            Assert.IsNotNull((object)fireDocumentController);
            Assert.AreEqual<string>
                ("127.0.0.1", ((BaseService)fireDocumentController).Server);
            Assert.AreEqual<int>(8080, ((BaseService)fireDocumentController).Port);
        }

        [TestMethod()]
        public void EditTest()
        {
            FireDocumentController fireDocumentController;
            //测试用例1
            fireDocumentController = new FireDocumentController();
            fireDocumentController.Edit((Fire_Document)null);
            Assert.IsNotNull((object)fireDocumentController);
            Assert.AreEqual<string>
                ("127.0.0.1", ((BaseService)fireDocumentController).Server);
            Assert.AreEqual<int>(8080, ((BaseService)fireDocumentController).Port);
            // 测试用例2
            fireDocumentController = new FireDocumentController();
            Fire_Document s0 = new Fire_Document();
            s0.OBJECTID = 0;
            s0.shape = (string)null;
            s0.city = (string)null;
            s0.county = (string)null;
            s0.no = (string)null;
            s0.hotid = (string)null;
            s0.name = (string)null;
            s0.address = (string)null;
            s0.longitude = default(double?);
            s0.latitude = default(double?);
            s0.s_time = (string)null;
            s0.f_time = (string)null;
            s0.e_time = (string)null;
            s0.duration = default(double?);
            s0.firetype = (string)null;
            s0.cause = (string)null;
            s0.firearea = default(double?);
            s0.nf_area = default(double?);
            s0.af_proport = default(double?);
            s0.t_categ = (string)null;
            s0.ta_categ = (string)null;
            s0.d_categ = (string)null;
            s0.treeform = (string)null;
            s0.woodloss = default(double?);
            s0.iwoodloss = default(double?);
            s0.saplloss = default(double?);
            s0.inj_minor = default(int?);
            s0.inj_severe = default(int?);
            s0.inj_death = default(int?);
            s0.conductor = (string)null;
            s0.con_post = (string)null;
            s0.brigade = default(int?);
            s0.for_police = default(int?);
            s0.army = default(int?);
            s0.arm_police = default(int?);
            s0.masses = default(int?);
            s0.plane = default(int?);
            s0.planetype = (string)null;
            s0.flighttime = default(double?);
            s0.flightcost = default(double?);
            s0.planefall = default(int?);
            s0.fallpeople = default(int?);
            s0.p_chemical = default(int?);
            s0.p_bucket = default(int?);
            s0.commandcar = default(int?);
            s0.trans_car = default(int?);
            s0.armoredcar = default(int?);
            s0.othercar = default(int?);
            s0.shortwave = default(int?);
            s0.uswave = default(int?);
            s0.windequip = default(int?);
            s0.watergun = default(int?);
            s0.n2n3tool = default(int?);
            s0.otherequip = default(int?);
            s0.fightcost = default(double?);
            s0.otherloss = default(double?);
            s0.wrecker = (string)null;
            s0.wreckerage = 0;
            s0.wreckerpro = (string)null;
            s0.wreckerunit = (string)null;
            s0.wapunish = (string)null;
            s0.wcpunish = (string)null;
            s0.hapunish = (string)null;
            s0.hcpunish = (string)null;
            s0.tempera = default(double?);
            s0.humidity = default(double?);
            s0.winddir = (string)null;
            s0.windpower = (string)null;
            s0.windspeed = default(double?);
            s0.rainfall = default(double?);
            s0.description = (string)null;
            s0.cre_time = (string)null;
            s0.cre_pers = (string)null;
            s0.mod_time = (string)null;
            s0.mod_pers = (string)null;
            s0.picture1 = (string)null;
            s0.picture2 = (string)null;
            s0.video = (string)null;
            s0.id = (string)null;
            s0.province = (string)null;
            s0.town_name = (string)null;
            s0.village_name = (string)null;
            s0.elevation = default(double?);
            s0.aspect = (string)null;
            s0.slope_position = (string)null;
            s0.slope = default(double?);
            s0.land_type = (string)null;
            s0.front_command_name = (string)null;
            s0.front_command_post = (string)null;
            s0.rear_command_name = (string)null;
            s0.rear_command_post = (string)null;
            s0.cadre = default(int?);
            s0.for_cop = default(int?);
            s0.brigade_people = default(int?);
            s0.hbrigade_people = default(int?);
            s0.hbrigade = default(int?);
            s0.communication_car = default(int?);
            s0.support_car = default(int?);
            s0.hpw_tanker = default(int?);
            s0.bulldozer = default(int?);
            s0.interphone = default(int?);
            s0.satellitephone = default(int?);
            s0.other_communication = default(int?);
            s0.nav_handheld = default(int?);
            s0.nav_vehicle = default(int?);
            s0.high_pressure_fex = default(int?);
            s0.pump = default(int?);
            s0.artificial_rain = default(double?);
            s0.fire_bombs = default(int?);
            s0.b_cutter = default(int?);
            s0.chainsaw = default(int?);
            s0.camera1 = default(int?);
            s0.camera2 = default(int?);
            s0.caseInfo = (string)null;
            s0.wayofaccident = (string)null;
            s0.weather = (string)null;
            s0.high_tempera = default(double?);
            s0.low_tempera = default(double?);
            s0.low_humidity = default(double?);
            s0.code = (string)null;
            s0.forestarea = default(double?);
            s0.newforestarea = default(double?);
            s0.artificialfireout = default(int?);
            s0.totavehiclenumber = default(int?);
            s0.carnumber = default(int?);
            s0.planeoutnumber = default(int?);
            s0.WingAirPlaneNumber = default(int?);
            s0.WingAirPlaneTime = default(int?);
            s0.HelicopterNumber = default(int?);
            s0.HelicopterTime = default(int?);
            s0.WuRenJiNumber = default(int?);
            s0.WuRenjiTime = default(int?);
            s0.IsDealWith = default(int?);
            s0.ProcessedNumber = default(int?);
            s0.CriminalNumber = default(int?);
            s0.APenaltyNumber = default(int?);
            s0.ASanctionNumber = default(int?);
            s0.RecordDispositionNumber = default(int?);
            s0.Reporter = (string)null;
            s0.ReportTime = (string)null;
            s0.pac = (string)null;
            s0.mediaByteDict = (Dictionary<string, object>)null;
            s0.mediaFiles = (List<MediaFile>)null;
            fireDocumentController.Edit(s0);
            Assert.IsNotNull((object)fireDocumentController);
            Assert.AreEqual<string>
                ("127.0.0.1", ((BaseService)fireDocumentController).Server);
            Assert.AreEqual<int>(8080, ((BaseService)fireDocumentController).Port);
            // 测试用例3
            fireDocumentController = new FireDocumentController();
            s0 = new Fire_Document();
            s0.OBJECTID = 0;
            s0.shape = "";
            s0.city = (string)null;
            s0.county = (string)null;
            s0.no = (string)null;
            s0.hotid = (string)null;
            s0.name = (string)null;
            s0.address = (string)null;
            s0.longitude = default(double?);
            s0.latitude = default(double?);
            s0.s_time = (string)null;
            s0.f_time = (string)null;
            s0.e_time = (string)null;
            s0.duration = default(double?);
            s0.firetype = (string)null;
            s0.cause = (string)null;
            s0.firearea = default(double?);
            s0.nf_area = default(double?);
            s0.af_proport = default(double?);
            s0.t_categ = (string)null;
            s0.ta_categ = (string)null;
            s0.d_categ = (string)null;
            s0.treeform = (string)null;
            s0.woodloss = default(double?);
            s0.iwoodloss = default(double?);
            s0.saplloss = default(double?);
            s0.inj_minor = default(int?);
            s0.inj_severe = default(int?);
            s0.inj_death = default(int?);
            s0.conductor = (string)null;
            s0.con_post = (string)null;
            s0.brigade = default(int?);
            s0.for_police = default(int?);
            s0.army = default(int?);
            s0.arm_police = default(int?);
            s0.masses = default(int?);
            s0.plane = default(int?);
            s0.planetype = (string)null;
            s0.flighttime = default(double?);
            s0.flightcost = default(double?);
            s0.planefall = default(int?);
            s0.fallpeople = default(int?);
            s0.p_chemical = default(int?);
            s0.p_bucket = default(int?);
            s0.commandcar = default(int?);
            s0.trans_car = default(int?);
            s0.armoredcar = default(int?);
            s0.othercar = default(int?);
            s0.shortwave = default(int?);
            s0.uswave = default(int?);
            s0.windequip = default(int?);
            s0.watergun = default(int?);
            s0.n2n3tool = default(int?);
            s0.otherequip = default(int?);
            s0.fightcost = default(double?);
            s0.otherloss = default(double?);
            s0.wrecker = (string)null;
            s0.wreckerage = 0;
            s0.wreckerpro = (string)null;
            s0.wreckerunit = (string)null;
            s0.wapunish = (string)null;
            s0.wcpunish = (string)null;
            s0.hapunish = (string)null;
            s0.hcpunish = (string)null;
            s0.tempera = default(double?);
            s0.humidity = default(double?);
            s0.winddir = (string)null;
            s0.windpower = (string)null;
            s0.windspeed = default(double?);
            s0.rainfall = default(double?);
            s0.description = (string)null;
            s0.cre_time = (string)null;
            s0.cre_pers = (string)null;
            s0.mod_time = (string)null;
            s0.mod_pers = (string)null;
            s0.picture1 = (string)null;
            s0.picture2 = (string)null;
            s0.video = (string)null;
            s0.id = (string)null;
            s0.province = (string)null;
            s0.town_name = (string)null;
            s0.village_name = (string)null;
            s0.elevation = default(double?);
            s0.aspect = (string)null;
            s0.slope_position = (string)null;
            s0.slope = default(double?);
            s0.land_type = (string)null;
            s0.front_command_name = (string)null;
            s0.front_command_post = (string)null;
            s0.rear_command_name = (string)null;
            s0.rear_command_post = (string)null;
            s0.cadre = default(int?);
            s0.for_cop = default(int?);
            s0.brigade_people = default(int?);
            s0.hbrigade_people = default(int?);
            s0.hbrigade = default(int?);
            s0.communication_car = default(int?);
            s0.support_car = default(int?);
            s0.hpw_tanker = default(int?);
            s0.bulldozer = default(int?);
            s0.interphone = default(int?);
            s0.satellitephone = default(int?);
            s0.other_communication = default(int?);
            s0.nav_handheld = default(int?);
            s0.nav_vehicle = default(int?);
            s0.high_pressure_fex = default(int?);
            s0.pump = default(int?);
            s0.artificial_rain = default(double?);
            s0.fire_bombs = default(int?);
            s0.b_cutter = default(int?);
            s0.chainsaw = default(int?);
            s0.camera1 = default(int?);
            s0.camera2 = default(int?);
            s0.caseInfo = (string)null;
            s0.wayofaccident = (string)null;
            s0.weather = (string)null;
            s0.high_tempera = default(double?);
            s0.low_tempera = default(double?);
            s0.low_humidity = default(double?);
            s0.code = (string)null;
            s0.forestarea = default(double?);
            s0.newforestarea = default(double?);
            s0.artificialfireout = default(int?);
            s0.totavehiclenumber = default(int?);
            s0.carnumber = default(int?);
            s0.planeoutnumber = default(int?);
            s0.WingAirPlaneNumber = default(int?);
            s0.WingAirPlaneTime = default(int?);
            s0.HelicopterNumber = default(int?);
            s0.HelicopterTime = default(int?);
            s0.WuRenJiNumber = default(int?);
            s0.WuRenjiTime = default(int?);
            s0.IsDealWith = default(int?);
            s0.ProcessedNumber = default(int?);
            s0.CriminalNumber = default(int?);
            s0.APenaltyNumber = default(int?);
            s0.ASanctionNumber = default(int?);
            s0.RecordDispositionNumber = default(int?);
            s0.Reporter = (string)null;
            s0.ReportTime = (string)null;
            s0.pac = (string)null;
            s0.mediaByteDict = (Dictionary<string, object>)null;
            s0.mediaFiles = (List<MediaFile>)null;
            fireDocumentController.Edit(s0);
            Assert.IsNotNull((object)fireDocumentController);
            Assert.AreEqual<string>
                ("127.0.0.1", ((BaseService)fireDocumentController).Server);
            Assert.AreEqual<int>(8080, ((BaseService)fireDocumentController).Port);
        }

        [TestMethod()]
        public void DeleteTest()
        {
            FireDocumentController fireDocumentController;
            // 测试用例1 
            fireDocumentController = new FireDocumentController();
            fireDocumentController.Delete( (Dictionary<string, object>)null);
            Assert.IsNotNull((object)fireDocumentController);
            Assert.AreEqual<string>
                ("127.0.0.1", ((BaseService)fireDocumentController).Server);
            Assert.AreEqual<int>(8080, ((BaseService)fireDocumentController).Port);
            //测试用例2
            Dictionary<string, object> dictionary;
            fireDocumentController = new FireDocumentController();
            dictionary = new Dictionary<string, object>(0);
            dictionary[""] = (object)null;
            fireDocumentController.Delete(dictionary);
            Assert.IsNotNull((object)fireDocumentController);
            Assert.AreEqual<string>
                ("127.0.0.1", ((BaseService)fireDocumentController).Server);
            Assert.AreEqual<int>(8080, ((BaseService)fireDocumentController).Port);
        }

        [TestMethod()]
        public void AddMediaTest()
        {
            FireDocumentController fireDocumentController;
            //测试用例1
            fireDocumentController = new FireDocumentController();
            fireDocumentController.AddMedia((Dictionary<string, object>)null, (Dictionary<string, object>)null);
            Assert.IsNotNull((object)fireDocumentController);
            Assert.AreEqual<string>("127.0.0.1", ((BaseService)fireDocumentController).Server);
            Assert.AreEqual<int>(8080, ((BaseService)fireDocumentController).Port);
            //测试用例2
            Dictionary<string, object> dictionary;
            fireDocumentController = new FireDocumentController();
            dictionary = new Dictionary<string, object>(0);
            dictionary[""] = (object)null;
            fireDocumentController.AddMedia(dictionary, (Dictionary<string, object>)null);
            Assert.IsNotNull((object)fireDocumentController);
            Assert.AreEqual<string>("127.0.0.1", ((BaseService)fireDocumentController).Server);
            Assert.AreEqual<int>(8080, ((BaseService)fireDocumentController).Port);
        }

        [TestMethod()]
        public void DeleteMediaTest()
        {
            FireDocumentController fireDocumentController;
            // 测试用例1
            fireDocumentController = new FireDocumentController();
            fireDocumentController.DeleteMedia((Dictionary<string, object>)null);
            Assert.IsNotNull((object)fireDocumentController);
            Assert.AreEqual<string>
                ("127.0.0.1", ((BaseService)fireDocumentController).Server);
            Assert.AreEqual<int>(8080, ((BaseService)fireDocumentController).Port);
            //测试用例2
            Dictionary<string, object> dictionary;
            fireDocumentController = new FireDocumentController();
            dictionary = new Dictionary<string, object>(0);
            dictionary[""] = (object)null;
            fireDocumentController.DeleteMedia( dictionary);
            Assert.IsNotNull((object)fireDocumentController);
            Assert.AreEqual<string>
                ("127.0.0.1", ((BaseService)fireDocumentController).Server);
            Assert.AreEqual<int>(8080, ((BaseService)fireDocumentController).Port);
        }

        [TestMethod()]
        public void DeleteTest1()
        {
            FireDocumentController fireDocumentController;
            fireDocumentController = new FireDocumentController();
            fireDocumentController.Delete((string)null);
            Assert.IsNotNull((object)fireDocumentController);
            Assert.AreEqual<string>
                ("127.0.0.1", ((BaseService)fireDocumentController).Server);
            Assert.AreEqual<int>(8080, ((BaseService)fireDocumentController).Port);
        }

        [TestMethod()]
        public void AddMediaTest1()
        {
            FireDocumentController fireDocumentController;
            fireDocumentController = new FireDocumentController();
            fireDocumentController.AddMedia
                ((string)null, (Dictionary<string, object>)null);
            Assert.IsNotNull((object)fireDocumentController);
            Assert.AreEqual<string>
                ("127.0.0.1", ((BaseService)fireDocumentController).Server);
            Assert.AreEqual<int>(8080, ((BaseService)fireDocumentController).Port);
        }

        [TestMethod()]
        public void DeleteMediaTest1()
        {
            FireDocumentController fireDocumentController;
            fireDocumentController = new FireDocumentController();
            fireDocumentController.DeleteMedia((string)null);
            Assert.IsNotNull((object)fireDocumentController);
            Assert.AreEqual<string>
                ("127.0.0.1", ((BaseService)fireDocumentController).Server);
            Assert.AreEqual<int>(8080, ((BaseService)fireDocumentController).Port);
        }
    }
}